env:
  browser: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:compat/recommended
  - plugin:unicorn/recommended
  - plugin:vue/recommended
  - prettier
plugins:
  - svelte3
parserOptions:
  ecmaVersion: 6
  sourceType: module
overrides:
  - files: "*.svelte"
    processor: "svelte3/svelte3"
